//! `check-knowledge` parity tests: four check slices (`mini`, `mini-bad`,
//! `mini-stale`, `root`), byte-compared verbatim against the compiled
//! binary, and the CLI's load-failure-vs-check-finding boundary (the
//! CLI-failure-path deviation and the eager-glob-validation deviation).
//!
//! The four slices sit in reviewed, Rust-generated goldens
//! (`tests/goldens/check/`, regenerated by `cargo run --bin gen-goldens`).
//! `check-knowledge`'s "generated file is out of date" hint names
//! `houserules render`, which the frozen JS at `common::FROZEN_SHA`
//! cannot produce.

mod common;

use std::fs;

use common::{FrozenWorktree, copy_dir_recursive, houserules, repo_root};

/// One frozen `tests/goldens/check/<slice>.json` capture: `stdout`,
/// `stderr`, and `exit`, read directly from the corpus file rather than
/// hand-copied, so a corpus regeneration is the only way this test's
/// expectation can drift.
struct CorpusCheck {
    stdout: String,
    stderr: String,
    exit: i32,
}

fn corpus_check(slice: &str) -> CorpusCheck {
    let text = fs::read_to_string(repo_root().join(format!("tests/goldens/check/{slice}.json")))
        .expect("read corpus check slice");
    let value: serde_json::Value = serde_json::from_str(&text).expect("parse corpus check slice");
    CorpusCheck {
        stdout: value["stdout"].as_str().expect("stdout").to_string(),
        stderr: value["stderr"].as_str().expect("stderr").to_string(),
        exit: value["exit"].as_i64().expect("exit") as i32,
    }
}

fn assert_matches_corpus(dir: &std::path::Path, slice: &str) {
    let expected = corpus_check(slice);
    let output = houserules()
        .args(["check-knowledge", "--dir"])
        .arg(dir)
        .output()
        .expect("run check-knowledge");
    assert_eq!(
        String::from_utf8(output.stdout).expect("utf8 stdout"),
        expected.stdout,
        "{slice}: stdout diverged from the frozen corpus"
    );
    assert_eq!(
        String::from_utf8(output.stderr).expect("utf8 stderr"),
        expected.stderr,
        "{slice}: stderr diverged from the frozen corpus"
    );
    assert_eq!(
        output.status.code(),
        Some(expected.exit),
        "{slice}: exit code diverged from the frozen corpus"
    );
}

/// The `mini` fixture is a clean base -- `check-knowledge` there must
/// print `knowledge: ok` and exit 0, exactly as `tests/goldens/check/
/// mini.json` pins.
#[test]
fn check_knowledge_matches_the_frozen_mini_corpus() {
    assert_matches_corpus(&repo_root().join("tests/fixtures/mini"), "mini");
}

/// `mini-bad` seeds all nine `template/tools/lib/json-store.mjs` validator
/// message shapes plus every `checkBase`/`checkShape` per-entry shape (id
/// prefix, duplicate id, standing, `see`, `verify`, check-shape field and
/// regex errors, and the topic/file-name mismatch) --
/// `tests/goldens/check/mini-bad.json` pins the full 20-message stderr,
/// verbatim and in order, and exit 1.
#[test]
fn check_knowledge_matches_the_frozen_mini_bad_corpus() {
    assert_matches_corpus(&repo_root().join("tests/fixtures/mini-bad"), "mini-bad");
}

/// `mini-stale` is a base that passes the first (schema/shape) stage cleanly,
/// so `check_base` reaches its post-early-return checks -- a stale generated
/// file, a missing one, a stray file in `.claude/rules`, and both a byte and a
/// line budget overrun -- pinned by `tests/goldens/check/mini-stale.json`.
#[test]
fn check_knowledge_matches_the_frozen_mini_stale_corpus() {
    assert_matches_corpus(&repo_root().join("tests/fixtures/mini-stale"), "mini-stale");
}

/// This repository's own knowledge base, at the frozen sha, is clean --
/// `tests/goldens/check/root.json` pins `knowledge: ok`, exit 0, the same
/// as the `mini` slice but exercising this repository's real, larger
/// knowledge base end to end.
///
/// Renders first: the frozen worktree's own checked-in `.claude/rules/*.md`
/// and skill file are generated by the FROZEN JS at `common::FROZEN_SHA`, so
/// they still say `tools/kb.sh render` -- the current binary's own `houserules
/// render` would call them stale on sight. `render_parity.rs`'s own root test
/// faces the identical fact and deletes then re-renders before comparing; this
/// test renders in place instead (the golden itself was captured the same way,
/// `gen-goldens.rs`'s own doc has the account), so what it checks is what an
/// adopter running `houserules render && houserules check-knowledge` back to
/// back would see: current, not the frozen sha's own now-stale generated
/// files.
#[test]
fn check_knowledge_matches_the_frozen_root_corpus() {
    let worktree = FrozenWorktree::checkout(&repo_root(), common::FROZEN_SHA);
    let render_output = houserules()
        .args(["render", "--dir"])
        .arg(&worktree.path)
        .output()
        .expect("run render");
    assert!(
        render_output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&render_output.stderr)
    );
    assert_matches_corpus(&worktree.path, "root");
}

/// `check-knowledge` reuses `load_base`, so a malformed `areas.json` glob
/// fails at load time, one named line, exit 2 -- distinct from a base
/// that loads fine and fails the check itself (`mini-bad`/`mini-stale`
/// above, both exit 1 with the ported `checkBase` stderr messages). This
/// pins the boundary between the two: a base that fails to load, side by
/// side with a base that loads and fails the check.
#[test]
fn check_knowledge_fails_on_a_malformed_area_glob_with_a_named_error() {
    let dir = tempfile::tempdir().expect("tempdir");
    copy_dir_recursive(&repo_root().join("tests/fixtures/mini"), dir.path());
    let areas_path = dir.path().join("knowledge/areas.json");
    let areas_text = fs::read_to_string(&areas_path).expect("read areas.json");
    assert!(
        areas_text.contains("\"mini-tools/**\""),
        "fixture shape changed, update this test's injected glob"
    );
    let mangled = areas_text.replace("\"mini-tools/**\"", "\"mini-tools/**\", \"a[z-a]b\"");
    fs::write(&areas_path, mangled).expect("write a malformed glob into areas.json");

    let output = houserules()
        .args(["check-knowledge", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run check-knowledge");

    assert_eq!(output.status.code(), Some(2), "malformed-glob exit code");
    assert_eq!(output.stdout, b"", "no stdout on the load-failure path");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert_eq!(stderr.lines().count(), 1, "exactly one named error line");
    assert!(
        stderr.contains("a[z-a]b"),
        "the error names the offending glob, got: {stderr:?}"
    );
}

/// Load-failure error arm 2 of 2: `check-knowledge --dir` at a directory
/// with no `knowledge/` at all fails the same way `render` does (both
/// call `load_base`), one named line naming `schema.json`, exit 2.
#[test]
fn check_knowledge_missing_knowledge_directory_prints_a_named_error_and_exits_2() {
    let dir = tempfile::tempdir().expect("tempdir");

    let output = houserules()
        .args(["check-knowledge", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run check-knowledge");

    assert_eq!(output.status.code(), Some(2), "load_base failure exit code");
    assert_eq!(output.stdout, b"", "no stdout on the error path");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert_eq!(stderr.lines().count(), 1, "exactly one named error line");
    assert!(
        stderr.contains("schema.json"),
        "the error names the missing file, got: {stderr:?}"
    );
}

/// Load-failure error arm, git-resolution leg: `check-knowledge` with
/// `--dir` omitted outside any git repository falls back to
/// `repo_root_from_cwd` (shared with `render`), fails the same way.
#[test]
fn check_knowledge_outside_a_git_repository_prints_a_named_error_and_exits_2() {
    let dir = tempfile::tempdir().expect("tempdir");

    let output = houserules()
        .arg("check-knowledge")
        .current_dir(dir.path())
        .output()
        .expect("run check-knowledge");

    assert_eq!(
        output.status.code(),
        Some(2),
        "git-root-resolution failure exit code"
    );
    assert_eq!(output.stdout, b"", "no stdout on the error path");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert_eq!(stderr.lines().count(), 1, "exactly one named error line");
    assert!(!stderr.trim().is_empty(), "the error line is not empty");
}

// ---- the ruled clap argv deviation, for `check-knowledge`: probing an
// unknown flag or unexpected positional live (`tools/kb.mjs check
// --bogus`/`extra`) finds the same JS-ignores-it-and-succeeds divergence
// every other flat command has, even though `check-knowledge` takes no
// value-bearing flag or positional beyond `--dir`.

/// `check-knowledge --bogus`: JS ignores the unrecognized flag and checks
/// (exit 0, `knowledge: ok`); the binary reports it as an unexpected
/// argument, exit 2.
#[test]
fn check_knowledge_with_an_unknown_flag_exits_2_where_js_ignored_it_and_succeeded() {
    let output = houserules()
        .args(["check-knowledge", "--bogus", "--dir"])
        .arg(repo_root().join("tests/fixtures/mini"))
        .output()
        .expect("run check-knowledge --bogus");
    assert_eq!(output.status.code(), Some(2));
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.starts_with("error: unexpected argument '--bogus' found"),
        "got: {stderr:?}"
    );
}

/// `check-knowledge extra`: JS ignores the unexpected positional and
/// checks (exit 0); the binary reports it as an unexpected argument,
/// exit 2.
#[test]
fn check_knowledge_with_an_unexpected_positional_exits_2_where_js_ignored_it_and_succeeded() {
    let output = houserules()
        .args(["check-knowledge", "extra", "--dir"])
        .arg(repo_root().join("tests/fixtures/mini"))
        .output()
        .expect("run check-knowledge extra");
    assert_eq!(output.status.code(), Some(2));
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.starts_with("error: unexpected argument 'extra' found"),
        "got: {stderr:?}"
    );
}

/// `render --check` exits 1 while stale, `render` writes, then
/// `check-knowledge` reports and passes -- the render half and the check
/// half exercised together, back to back.
#[test]
fn render_check_exits_1_while_stale_render_writes_check_reports_and_passes() {
    let dir = tempfile::tempdir().expect("tempdir");
    copy_dir_recursive(&repo_root().join("tests/fixtures/mini"), dir.path());
    fs::remove_dir_all(dir.path().join(".claude/rules")).expect("remove .claude/rules");
    fs::remove_file(dir.path().join(".claude/skills/project-knowledge/SKILL.md"))
        .expect("remove the knowledge skill");

    let output = houserules()
        .args(["render", "--check", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run render --check");
    assert_eq!(output.status.code(), Some(1), "render --check while stale");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert!(
        stderr.contains(".claude/rules/standing-rules.md: would change\n"),
        "got: {stderr:?}"
    );

    let output = houserules()
        .args(["check-knowledge", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run check-knowledge while stale");
    assert_eq!(output.status.code(), Some(1), "check-knowledge while stale");
    let stderr = String::from_utf8(output.stderr).expect("utf8 stderr");
    assert!(
        stderr.contains("generated file is out of date"),
        "got: {stderr:?}"
    );

    let output = houserules()
        .args(["render", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run render");
    assert_eq!(output.status.code(), Some(0), "render writes");
    let stdout = String::from_utf8(output.stdout).expect("utf8 stdout");
    assert!(
        stdout.contains(".claude/rules/standing-rules.md: written\n"),
        "got: {stdout:?}"
    );

    let output = houserules()
        .args(["render", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run render again");
    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        String::from_utf8(output.stdout).expect("utf8 stdout"),
        "render: up to date\n"
    );

    let output = houserules()
        .args(["render", "--check", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run render --check once clean");
    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        String::from_utf8(output.stdout).expect("utf8 stdout"),
        "render: up to date\n"
    );

    let output = houserules()
        .args(["check-knowledge", "--dir"])
        .arg(dir.path())
        .output()
        .expect("run check-knowledge once clean");
    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        String::from_utf8(output.stdout).expect("utf8 stdout"),
        "knowledge: ok\n"
    );
}
