import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  FROZEN_SHA,
  generateCorpus,
  listFilesRecursive,
  sha256,
} from '../tools/make-corpus.mjs';
import { scratchDir } from './scratch-dir.mjs';

const COMMITTED = join(import.meta.dirname, 'corpus');

/**
 * `manifest.json` without its `node_version` field, as a comparable object.
 * `node_version` stamps the environment that generated the corpus, not the
 * frozen JS behavior the regeneration test asserts, so a node bump must not
 * read as a corpus mismatch: compare every other field, and the field's
 * presence, without pinning its value.
 */
function manifestWithoutNodeVersion(text) {
  const { node_version, ...rest } = JSON.parse(text);
  return { hadNodeVersion: typeof node_version === 'string' && node_version.length > 0, rest };
}

describe('the frozen fixture corpus (HR-054)', () => {
  it(
    'regenerates byte-identical to the committed corpus, node_version aside',
    () => {
      const outDir = scratchDir('corpus-gen-');
      const { files } = generateCorpus({ outDir });
      const committedFiles = listFilesRecursive(COMMITTED);

      expect(files).toEqual(committedFiles);

      const mismatches = files.filter((relPath) => {
        const generated = readFileSync(join(outDir, relPath));
        const committed = readFileSync(join(COMMITTED, relPath));
        if (relPath === 'manifest.json') {
          return (
            JSON.stringify(manifestWithoutNodeVersion(generated.toString('utf8'))) !==
            JSON.stringify(manifestWithoutNodeVersion(committed.toString('utf8')))
          );
        }
        return !generated.equals(committed);
      });
      expect(mismatches).toEqual([]);
    },
    30000,
  );

  it('the manifest pins the frozen sha and its inventory matches every corpus file', () => {
    const manifest = JSON.parse(
      readFileSync(join(COMMITTED, 'manifest.json'), 'utf8'),
    );
    expect(manifest.frozen_sha).toBe(FROZEN_SHA);
    const paths = Object.keys(manifest.inventory);
    expect(paths.length).toBeGreaterThan(0);
    for (const relPath of paths) {
      const abs = join(COMMITTED, relPath);
      expect(existsSync(abs)).toBe(true);
      expect(sha256(readFileSync(abs))).toBe(manifest.inventory[relPath]);
    }
  });

  it('freezes non-trivial render and check output', () => {
    const standing = readFileSync(
      join(COMMITTED, 'render/root/.claude/rules/standing-rules.md'),
      'utf8',
    );
    expect(standing).toContain('# Standing rules');
    expect(standing).toContain('[houserules.template-is-the-source]');

    const skill = readFileSync(
      join(COMMITTED, 'render/root/.claude/skills/project-knowledge/SKILL.md'),
      'utf8',
    );
    expect(skill).toContain('name: project-knowledge');

    const checkRuns = readdirSync(join(COMMITTED, 'check')).map((name) =>
      JSON.parse(readFileSync(join(COMMITTED, 'check', name), 'utf8')),
    );
    const failing = checkRuns.filter((run) => run.exit === 1);
    expect(failing.length).toBeGreaterThan(0);
    expect(failing.some((run) => run.stderr.includes('duplicate id'))).toBe(true);
  });

  it('freezes every message shape checkBase can emit', () => {
    // One exact, distinctive substring per checkBase/checkShape/checkBudget
    // message template, plus the nine generic schema-validator shapes.
    // mini-bad seeds the shapes that accumulate before checkBase's early
    // return; mini-stale is schema-valid, so it reaches the five shapes
    // after that return (batch 16 task 1 review, finding 3; the enum shape
    // was still missing at round 1 — round 2 new_breakage finding 1).
    const shapes = [
      'area "cli" is missing',
      'unknown area "bogus"',
      'longer than 160 characters',
      '.body: must be array',
      'must match ^\\d{4}-\\d{2}-\\d{2}$',
      '.summary: shorter than 1',
      '.check.body_line_max: below 1',
      '.tags: items must be unique',
      'missing "tags"',
      'unknown field "nickname"',
      'duplicate id (also in',
      'id must start with "entries."',
      'standing needs kind rule or invariant',
      'see "entries.nonexistent" does not exist',
      'verify path "nonexistent/path-xyz.txt" does not exist',
      'needs "files"',
      'needs "subject", "body_absent", or "body_line_max"',
      'is not a valid regex',
      'must equal the file name "mismatch"',
      'must be one of "rule", "invariant", "gotcha", "procedure", "decision", "history"',
      'generated file is out of date',
      'not generated by kb; remove it',
      'bytes, budget 12288',
      'lines, budget 160',
      'SKILL.md: missing',
    ];
    const allStderr = readdirSync(join(COMMITTED, 'check'))
      .map((name) => JSON.parse(readFileSync(join(COMMITTED, 'check', name), 'utf8')).stderr)
      .join('\n');
    const absent = shapes.filter((shape) => !allStderr.includes(shape));
    expect(absent).toEqual([]);
  });

  it('discloses every path normalization in the manifest and the frozen bytes', () => {
    const manifest = JSON.parse(readFileSync(join(COMMITTED, 'manifest.json'), 'utf8'));
    expect(manifest.normalizations.length).toBeGreaterThan(0);
    for (const normalization of manifest.normalizations) {
      expect(normalization.substituted).toMatch(/^<.+>\//);
      const content = readFileSync(join(COMMITTED, normalization.slice), 'utf8');
      expect(content).toContain(normalization.substituted);
    }
    // No real absolute path from the generating machine survives into the
    // slice the redaction targets (batch 16 task 1 review, finding 4).
    for (const name of readdirSync(join(COMMITTED, 'validate'))) {
      const text = readFileSync(join(COMMITTED, 'validate', name), 'utf8');
      expect(text).not.toMatch(/\/(home|tmp|private)\//);
    }
  });

  it('freezes at least one failing validate run', () => {
    const validateRuns = readdirSync(join(COMMITTED, 'validate')).map((name) =>
      JSON.parse(readFileSync(join(COMMITTED, 'validate', name), 'utf8')),
    );
    expect(validateRuns.some((run) => run.exit !== 0)).toBe(true);
  });

  it('freezes the skipped>0 validate message naming --report (batch 17 T1)', () => {
    const run = JSON.parse(
      readFileSync(join(COMMITTED, 'validate/skipped-report.json'), 'utf8'),
    );
    expect(run.exit).toBe(1);
    expect(run.stdout).toContain(
      'self_audit.summary.skipped is 1; re-run audit with --report',
    );
  });

  it('freezes a stats slice over the committed batch-14 workspace fixtures', () => {
    // This slice exercises stats()'s reviews input path only: the fixture
    // holds no task-*-audit*.json, so audits and unused_ids stay
    // structurally empty here. stats/stats-workspace.json (below) is the
    // slice that exercises the audits path and the unused_ids
    // cross-reference (batch 17 T1 fix round 1, review issue 4).
    const run = JSON.parse(
      readFileSync(join(COMMITTED, 'stats/batch14-workspace.json'), 'utf8'),
    );
    expect(run.exit).toBe(0);
    const stats = JSON.parse(run.stdout);
    expect(stats.reviews.files).toBeGreaterThan(0);
    expect(stats.violations.length).toBeGreaterThan(0);
  });

  it('freezes a stats slice over a workspace with an audit file and a report (violations, unused_ids, audits, and the knowledge_used cross-reference all pinned)', () => {
    const run = JSON.parse(
      readFileSync(join(COMMITTED, 'stats/stats-workspace.json'), 'utf8'),
    );
    expect(run.exit).toBe(0);
    const stats = JSON.parse(run.stdout);
    expect(stats.audits.files).toBeGreaterThan(0);
    expect(stats.audits.tasks).toBeGreaterThan(0);
    expect(stats.violations.length).toBeGreaterThan(0);
    // The fixture's report cites exactly one of the audit file's two injected
    // ids in knowledge_used, so unused_ids must filter that one out -- a port
    // that never reads knowledge_used would leave both ids unused instead of
    // just the uncited one (batch 17 T1 fix round 2, review r1 new_breakage (c)).
    expect(stats.unused_ids.map((u) => u.id)).toEqual(['quality.principles']);
  });

  it('freezes the set-written bytes backlog.mjs produces for a status+batch change', () => {
    const run = JSON.parse(
      readFileSync(join(COMMITTED, 'backlog/set/mini/command.json'), 'utf8'),
    );
    expect(run.exit).toBe(0);
    expect(run.stdout).toBe('HR-901: status=done batch=2\n');
    const written = readFileSync(
      join(COMMITTED, 'backlog/set/mini/backlog/items/misc.json'),
      'utf8',
    );
    expect(written).toContain('"status": "done"');
    expect(written).toContain('"batch": 2');
  });
});
